server:
  port: 8083

spring:
  #Application
  application:
    name: quest-notification

quest-notification:
  kafka:
    consumer:
      applicationId: questEventPlayer
      internalTopic: game-event-topic
      externalTopic: external-output-notificaiton
      group-id: group-game-event-consumer
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      enable-auto-commit: false
